version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Utilisation de la variable d'environnement
    secrets:
      - postgres_password
    volumes:
      - dbdata:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hannon.delphine@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}  # Utilisation de la variable d'environnement
    depends_on:
      - db
    ports:
      - "5050:80"
    secrets:
      - pgadmin_password

networks:
  mynetwork:
    driver: bridge

volumes:
  dbdata:

secrets:
  postgres_password:
    external: true
  pgadmin_password:
    external: true
